---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7-1.test.shakeyoncloud.com
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: rhel-7-1.test.shakeyoncloud.com
    image: registry.redhat.io/ubi7/ubi
    pre_build_image: true
  - name: centos-8-1.test.shakeyoncloud.com
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: rhel8-1.test.shakeyoncloud.com
    image: registry.redhat.io/ubi8/ubi
    pre_build_image: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .
